name: PR label publish (RC artifact)

on:
  pull_request:
    types: [labeled, synchronize, reopened]

permissions:
  contents: read

jobs:
  rc:
    if: contains(github.event.pull_request.labels.*.name, 'publish')
    uses: ym-innowise/workflows-library/.github/workflows/gh-pack-rc.yml@v1
    with:
      node-version: '20'
      working-directory: '.'