name: PR label publish (release candidate)

on:
  pull_request:
    types: [labeled, synchronize, reopened]

permissions:
  contents: read

jobs:
  rc:
    if: contains(github.event.pull_request.labels.*.name, 'publish')
    uses: ym-innowise/workflows-library/.github/workflows/pr-label-publish.yml@main
    with:
      working-directory: '.'